CONSTRUCT {
   ?container_track_uri rdf:type Event:ComplexEvent ;
                        rdfs:label "Container Track" ;
                        Event:involvesEvent ?containerEvent .
    
    ?containerEvent ?pred ?subj .
}
WHERE {
    # a container track is the sequence of loads and discharges 
    # associated with a specific container
    
    # Query currently just selects all events associated with a 
    # single container. 
    # Do we need to split between separate container tracks of 
    # a single container during its lifetime? Then, when
    # does the containerID change?
	?containerEvent rdf:type ?type .
	FILTER(?type in (Event:LoadEvent, Event:DischargeEvent)) .
	?containerEvent Event:involvesDigitalTwin ?container .
	?container rdf:type DigitalTwin:Container ;
	           DigitalTwin:containerID ?containerID .
	
	# select all existing 
	?container_event ?pred ?subj. 
	
	# make unique URI for this container
	BIND ( URI( CONCAT ("https://ontology.tno.nl/logistics/federated/data#ContainerTrack_", STR(?containerID) ) )  as ?container_track_uri ) .            
	
}

# When does a container cease to exist? ( = when is the containerID changed?)